from copy import deepcopy


THUMBNAIL_URL = "/static/dashboard/assets/vh-media-logo.png"


LISTING_FIXTURES = [
    {
        "listingId": "1001001",
        "listingTitle": "Retro Camping Badge SVG Bundle",
        "listingUrl": "https://www.etsy.com/listing/1001001",
        "listingUrlVerified": False,
        "shopName": "North Ember Studio",
        "shopUrl": "https://www.etsy.com/shop/NorthEmberStudio",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 6.99,
        "totalShopSales": 18420,
        "views": 9321,
        "favorites": 1205,
        "goodReviews": 48,
        "createdDaysAgo": 11,
        "category": "craft-supplies-and-tools",
        "keywords": ["camping", "retro badge", "svg", "bundle", "outdoor"],
        "tags": [
            "camping svg",
            "retro camping",
            "badge svg bundle",
            "adventure shirt design",
            "outdoor svg",
            "national park svg",
            "camp mug design",
            "dad trip shirt",
            "vintage forest svg",
            "pod outdoor art",
            "rustic camping print",
            "explorer badge svg",
            "hiking graphic tee",
        ],
        "estimatedSalesMap": {"1": 14, "7": 83, "30": 264},
    },
    {
        "listingId": "1001002",
        "listingTitle": "Minimal Pantry Label Printable Set",
        "listingUrl": "https://www.etsy.com/listing/1001002",
        "listingUrlVerified": False,
        "shopName": "Paper House Grove",
        "shopUrl": "https://www.etsy.com/shop/PaperHouseGrove",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 8.5,
        "totalShopSales": 26780,
        "views": 12440,
        "favorites": 1890,
        "goodReviews": 66,
        "createdDaysAgo": 5,
        "category": "paper-and-party-supplies",
        "keywords": ["pantry labels", "printable labels", "kitchen organization", "minimalist"],
        "tags": [
            "pantry labels",
            "minimal pantry",
            "kitchen labels",
            "printable labels",
            "pantry organization",
            "editable pantry set",
            "jar label printable",
            "modern kitchen pdf",
            "home organization",
            "digital label set",
            "spice jar labels",
            "clean pantry style",
            "editable canva labels",
        ],
        "estimatedSalesMap": {"1": 22, "7": 97, "30": 301},
    },
    {
        "listingId": "1001003",
        "listingTitle": "Christian Easter SVG for POD Shirts",
        "listingUrl": "https://www.etsy.com/listing/1001003",
        "listingUrlVerified": False,
        "shopName": "Grace Thread Supply",
        "shopUrl": "https://www.etsy.com/shop/GraceThreadSupply",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 4.25,
        "totalShopSales": 14330,
        "views": 8050,
        "favorites": 936,
        "goodReviews": 34,
        "createdDaysAgo": 3,
        "category": "clothing",
        "keywords": ["christian svg", "easter svg", "pod shirt", "faith shirt"],
        "tags": [
            "christian svg",
            "easter shirt design",
            "faith svg",
            "he is risen svg",
            "pod easter tee",
            "religious shirt art",
            "cross svg bundle",
            "church event shirt",
            "resurrection sunday",
            "bible verse tee",
            "spring church merch",
            "christian pod design",
            "easter graphic tee",
        ],
        "estimatedSalesMap": {"1": 19, "7": 104, "30": 286},
    },
    {
        "listingId": "1001004",
        "listingTitle": "Wedding Welcome Sign Template",
        "listingUrl": "https://www.etsy.com/listing/1001004",
        "listingUrlVerified": False,
        "shopName": "Ivory Event Press",
        "shopUrl": "https://www.etsy.com/shop/IvoryEventPress",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 11.2,
        "totalShopSales": 22100,
        "views": 11880,
        "favorites": 1744,
        "goodReviews": 59,
        "createdDaysAgo": 18,
        "category": "weddings",
        "keywords": ["wedding sign", "editable canva", "welcome sign", "template"],
        "tags": [
            "wedding welcome sign",
            "editable canva sign",
            "modern wedding sign",
            "arch welcome board",
            "neutral wedding decor",
            "printable wedding sign",
            "templett sign template",
            "wedding entrance sign",
            "minimal wedding canva",
            "foam board wedding",
            "reception welcome sign",
            "digital wedding decor",
            "bridal sign template",
        ],
        "estimatedSalesMap": {"1": 12, "7": 76, "30": 245},
    },
    {
        "listingId": "1001005",
        "listingTitle": "Boho Wall Art Printable Trio",
        "listingUrl": "https://www.etsy.com/listing/1001005",
        "listingUrlVerified": False,
        "shopName": "Desert Line Prints",
        "shopUrl": "https://www.etsy.com/shop/DesertLinePrints",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 9.95,
        "totalShopSales": 19860,
        "views": 11305,
        "favorites": 2102,
        "goodReviews": 61,
        "createdDaysAgo": 27,
        "category": "art-and-collectibles",
        "keywords": ["boho wall art", "printable wall art", "neutral decor", "set of 3"],
        "tags": [
            "boho wall art",
            "neutral printable",
            "set of 3 prints",
            "minimal wall decor",
            "living room printable",
            "desert line art",
            "earth tone posters",
            "gallery wall set",
            "instant download art",
            "modern boho decor",
            "abstract wall print",
            "printable home decor",
            "beige wall art",
        ],
        "estimatedSalesMap": {"1": 16, "7": 91, "30": 288},
    },
    {
        "listingId": "1001006",
        "listingTitle": "Teacher Appreciation PNG Bundle",
        "listingUrl": "https://www.etsy.com/listing/1001006",
        "listingUrlVerified": False,
        "shopName": "Bright Bell Studio",
        "shopUrl": "https://www.etsy.com/shop/BrightBellStudio",
        "shopUrlVerified": False,
        "thumbnailUrl": THUMBNAIL_URL,
        "price": 5.5,
        "totalShopSales": 17340,
        "views": 8890,
        "favorites": 1010,
        "goodReviews": 43,
        "createdDaysAgo": 2,
        "category": "craft-supplies-and-tools",
        "keywords": ["teacher png", "appreciation bundle", "school shirt", "teacher gift"],
        "tags": [
            "teacher png",
            "teacher appreciation",
            "school shirt png",
            "gift for teacher",
            "classroom bundle",
            "sublimation teacher",
            "teacher life design",
            "end of year gift",
            "school svg png",
            "teacher tumbler art",
            "teacher quote bundle",
            "back to school png",
            "teacher sticker png",
        ],
        "estimatedSalesMap": {"1": 26, "7": 111, "30": 328},
    },
]


def get_listing_fixtures():
    return deepcopy(LISTING_FIXTURES)
