from copy import deepcopy 


KEYWORD_INSIGHTS =[
{
"keyword":"easter egg salad cap",
"sales":324 ,
"previousSales":24 ,
"growthPercent":1250 ,
"score":98 ,
"newListings":21 ,
"newListingsGrowthPercent":250 ,
"totalListings":13 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"holiday":"Easter",
"holidayDate":"Apr 5, 2026",
"holidayFit":"High",
"holidayReason":"Seasonal humor apparel and embroidered hats peak before Easter weekend in the USA.",
"intentTags":["easter","egg hunt","spring","brunch","funny hat","novelty gift"],
},
{
"keyword":"egg salad hat",
"sales":324 ,
"previousSales":24 ,
"growthPercent":1250 ,
"score":98 ,
"newListings":17 ,
"newListingsGrowthPercent":112 ,
"totalListings":18 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"holiday":"Easter",
"holidayDate":"Apr 5, 2026",
"holidayFit":"High",
"holidayReason":"Phrase-driven hat trend aligns with Easter brunch and novelty gift searches.",
"intentTags":["easter","egg hunt","spring","brunch","funny hat","novelty gift"],
},
{
"keyword":"golf rope hat",
"sales":315 ,
"previousSales":29 ,
"growthPercent":986 ,
"score":87 ,
"newListings":7 ,
"newListingsGrowthPercent":250 ,
"totalListings":578 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"holiday":"Father's Day",
"holidayDate":"Jun 21, 2026",
"holidayFit":"High",
"holidayReason":"Golf accessories spike in USA gift buying before Father's Day.",
"intentTags":["father day","dad gift","golf","golf dad","sports gift"],
},
{
"keyword":"funny golf hat",
"sales":327 ,
"previousSales":36 ,
"growthPercent":808 ,
"score":83 ,
"newListings":31 ,
"newListingsGrowthPercent":417 ,
"totalListings":1386 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"holiday":"Father's Day",
"holidayDate":"Jun 21, 2026",
"holidayFit":"High",
"holidayReason":"Humor plus golf is a strong POD gift angle for dads in the USA.",
"intentTags":["father day","dad gift","funny dad","golf","sports gift"],
},
{
"keyword":"teacher appreciation png",
"sales":253 ,
"previousSales":42 ,
"growthPercent":502 ,
"score":91 ,
"newListings":44 ,
"newListingsGrowthPercent":188 ,
"totalListings":922 ,
"physicalPercent":18 ,
"digitalPercent":82 ,
"holiday":"Teacher Appreciation Week",
"holidayDate":"May 4-8, 2026",
"holidayFit":"High",
"holidayReason":"Digital PNGs feed shirts, mugs, and classroom gifts during USA teacher gifting season.",
"intentTags":["teacher","teacher gift","classroom","school","educator","png","digital"],
},
{
"keyword":"mom floral svg",
"sales":241 ,
"previousSales":51 ,
"growthPercent":373 ,
"score":84 ,
"newListings":26 ,
"newListingsGrowthPercent":136 ,
"totalListings":1842 ,
"physicalPercent":34 ,
"digitalPercent":66 ,
"holiday":"Mother's Day",
"holidayDate":"May 10, 2026",
"holidayFit":"High",
"holidayReason":"Floral mom phrases convert well for shirts, cards, and digital cut files before Mother's Day.",
"intentTags":["mother day","mom gift","mama gift","gift for mom","floral","svg","digital"],
},
{
"keyword":"graduation stole svg",
"sales":198 ,
"previousSales":44 ,
"growthPercent":350 ,
"score":78 ,
"newListings":19 ,
"newListingsGrowthPercent":90 ,
"totalListings":511 ,
"physicalPercent":41 ,
"digitalPercent":59 ,
"holiday":"Graduation Season",
"holidayDate":"May-Jun 2026",
"holidayFit":"Medium",
"holidayReason":"USA graduation demand rises through May and June for custom apparel and digital files.",
"intentTags":["graduation","graduate","class of 2026","senior","school","svg"],
},
{
"keyword":"4th of july tumbler wrap",
"sales":187 ,
"previousSales":39 ,
"growthPercent":379 ,
"score":80 ,
"newListings":35 ,
"newListingsGrowthPercent":169 ,
"totalListings":764 ,
"physicalPercent":24 ,
"digitalPercent":76 ,
"holiday":"Independence Day",
"holidayDate":"Jul 4, 2026",
"holidayFit":"High",
"holidayReason":"Patriotic tumbler designs gain traction ahead of July 4 parties and gifts.",
"intentTags":["4th of july","independence day","patriotic","usa","tumbler","summer"],
},
{
"keyword":"back to school shirt",
"sales":173 ,
"previousSales":58 ,
"growthPercent":198 ,
"score":75 ,
"newListings":64 ,
"newListingsGrowthPercent":120 ,
"totalListings":2310 ,
"physicalPercent":88 ,
"digitalPercent":12 ,
"holiday":"Back to School",
"holidayDate":"Aug-Sep 2026",
"holidayFit":"Medium",
"holidayReason":"USA school-year kickoff supports teacher, student, and parent shirt demand.",
"intentTags":["back to school","teacher","student","classroom","school shirt"],
},
{
"keyword":"halloween ghost png",
"sales":166 ,
"previousSales":23 ,
"growthPercent":622 ,
"score":82 ,
"newListings":48 ,
"newListingsGrowthPercent":300 ,
"totalListings":1190 ,
"physicalPercent":16 ,
"digitalPercent":84 ,
"holiday":"Halloween",
"holidayDate":"Oct 31, 2026",
"holidayFit":"Medium",
"holidayReason":"Ghost graphics are early-build seasonal keywords for USA Halloween POD launches.",
"intentTags":["halloween","spooky","ghost","pumpkin","witch","png","digital"],
},
{
"keyword":"thanksgiving host gift",
"sales":141 ,
"previousSales":31 ,
"growthPercent":355 ,
"score":73 ,
"newListings":22 ,
"newListingsGrowthPercent":83 ,
"totalListings":670 ,
"physicalPercent":92 ,
"digitalPercent":8 ,
"holiday":"Thanksgiving",
"holidayDate":"Nov 26, 2026",
"holidayFit":"Medium",
"holidayReason":"Host gifts and home goods trend in USA search windows before Thanksgiving gatherings.",
"intentTags":["thanksgiving","host gift","hostess gift","family","kitchen","home decor"],
},
{
"keyword":"christmas teacher gift",
"sales":137 ,
"previousSales":18 ,
"growthPercent":661 ,
"score":79 ,
"newListings":29 ,
"newListingsGrowthPercent":142 ,
"totalListings":1508 ,
"physicalPercent":72 ,
"digitalPercent":28 ,
"holiday":"Christmas",
"holidayDate":"Dec 25, 2026",
"holidayFit":"Medium",
"holidayReason":"Teacher gifting ramps before USA Christmas break across mugs, ornaments, and printable cards.",
"intentTags":["christmas","xmas","holiday gift","teacher gift","ornament","mug"],
},
{
"keyword":"valentine classroom cards",
"sales":121 ,
"previousSales":17 ,
"growthPercent":612 ,
"score":77 ,
"newListings":33 ,
"newListingsGrowthPercent":175 ,
"totalListings":934 ,
"physicalPercent":31 ,
"digitalPercent":69 ,
"holiday":"Valentine's Day",
"holidayDate":"Feb 14, 2027",
"holidayFit":"Early",
"holidayReason":"Classroom card templates are digital-heavy and start building before Valentine's Day.",
"intentTags":["valentine","valentines","classroom","school","cards","love","heart"],
},
]


TOIDISPY_STYLE_KEYWORD_INSIGHTS =[
{
"keyword":"monopoly go partners",
"sales":663 ,
"previousSales":94 ,
"growthPercent":605 ,
"score":110 ,
"newListings":18 ,
"newListingsGrowthPercent":-61 ,
"totalListings":2295 ,
"physicalPercent":1 ,
"digitalPercent":99 ,
"intentTags":["monopoly","game","digital","partner","printable"],
},
{
"keyword":"high quality patch",
"sales":293 ,
"previousSales":8 ,
"growthPercent":3562 ,
"score":108 ,
"newListings":1 ,
"newListingsGrowthPercent":100 ,
"totalListings":414 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["patch","embroidery","badge","applique"],
},
{
"keyword":"cool patches",
"sales":301 ,
"previousSales":12 ,
"growthPercent":2408 ,
"score":107 ,
"newListings":3 ,
"newListingsGrowthPercent":200 ,
"totalListings":1356 ,
"physicalPercent":94 ,
"digitalPercent":6 ,
"intentTags":["patch","embroidery","jacket patch","hat patch"],
},
{
"keyword":"denim patches",
"sales":320 ,
"previousSales":18 ,
"growthPercent":1678 ,
"score":105 ,
"newListings":0 ,
"newListingsGrowthPercent":0 ,
"totalListings":1920 ,
"physicalPercent":99 ,
"digitalPercent":1 ,
"intentTags":["patch","denim","jacket","embroidery"],
},
{
"keyword":"funny golf hat",
"sales":327 ,
"previousSales":36 ,
"growthPercent":808 ,
"score":83 ,
"newListings":31 ,
"newListingsGrowthPercent":417 ,
"totalListings":1386 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["father day","dad gift","funny dad","golf","sports gift"],
},
{
"keyword":"easter egg salad cap",
"sales":324 ,
"previousSales":24 ,
"growthPercent":1250 ,
"score":98 ,
"newListings":21 ,
"newListingsGrowthPercent":250 ,
"totalListings":13 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["easter","egg hunt","spring","brunch","funny hat","novelty gift"],
},
{
"keyword":"mom floral svg",
"sales":241 ,
"previousSales":51 ,
"growthPercent":373 ,
"score":84 ,
"newListings":26 ,
"newListingsGrowthPercent":136 ,
"totalListings":1842 ,
"physicalPercent":34 ,
"digitalPercent":66 ,
"intentTags":["mother day","mom gift","mama gift","gift for mom","floral","svg","digital"],
},
{
"keyword":"teacher appreciation png",
"sales":253 ,
"previousSales":42 ,
"growthPercent":502 ,
"score":91 ,
"newListings":44 ,
"newListingsGrowthPercent":188 ,
"totalListings":922 ,
"physicalPercent":18 ,
"digitalPercent":82 ,
"intentTags":["teacher","teacher gift","classroom","school","educator","png","digital"],
},
{
"keyword":"halloween ghost png",
"sales":166 ,
"previousSales":23 ,
"growthPercent":622 ,
"score":82 ,
"newListings":48 ,
"newListingsGrowthPercent":300 ,
"totalListings":1190 ,
"physicalPercent":16 ,
"digitalPercent":84 ,
"intentTags":["halloween","spooky","ghost","pumpkin","witch","png","digital"],
},
{
"keyword":"christmas teacher gift",
"sales":137 ,
"previousSales":18 ,
"growthPercent":661 ,
"score":79 ,
"newListings":29 ,
"newListingsGrowthPercent":142 ,
"totalListings":1508 ,
"physicalPercent":72 ,
"digitalPercent":28 ,
"intentTags":["christmas","xmas","holiday gift","teacher gift","ornament","mug"],
},
{
"keyword":"peaches and cream zinnia seeds",
"sales":438 ,
"previousSales":66 ,
"growthPercent":563 ,
"score":96 ,
"newListings":9 ,
"newListingsGrowthPercent":80 ,
"totalListings":742 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["garden","seed","plant","flower","zinnia","botanical"],
},
{
"keyword":"personalized name necklace",
"sales":520 ,
"previousSales":115 ,
"growthPercent":352 ,
"score":102 ,
"newListings":14 ,
"newListingsGrowthPercent":27 ,
"totalListings":4820 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["jewelry","necklace","personalized","mother day","gift for her"],
},
{
"keyword":"later gator png",
"sales":184 ,
"previousSales":21 ,
"growthPercent":776 ,
"score":92 ,
"newListings":8 ,
"newListingsGrowthPercent":166 ,
"totalListings":318 ,
"physicalPercent":4 ,
"digitalPercent":96 ,
"intentTags":["png","digital","svg","funny","clipart","sublimation"],
},
{
"keyword":"national parks fabric",
"sales":211 ,
"previousSales":39 ,
"growthPercent":441 ,
"score":89 ,
"newListings":6 ,
"newListingsGrowthPercent":50 ,
"totalListings":684 ,
"physicalPercent":100 ,
"digitalPercent":0 ,
"intentTags":["fabric","sewing","quilt","national parks","wilderness","outdoor"],
},
]


def lay_thong_tin_tu_khoa ():
    return deepcopy (TOIDISPY_STYLE_KEYWORD_INSIGHTS )
